name: Build and Upload Artifact
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate a file
        run: echo "This is a test artifact" > artifact.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: artifact.txt
